services:
  mysql:
    image: 'mysql:9'
    environment:
      - 'MYSQL_DATABASE=simpleDatabase'
      - 'MYSQL_PASSWORD=password123'
      - 'MYSQL_ROOT_PASSWORD=rootpassword123'
      - 'MYSQL_USER=kirikos'
    ports:
      - '3306:3306'