spring.application.name=simpleWebApp

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/simpleDatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:kirikos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password123}

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace